version: '3.8'
services:
  agent-autonomo:
    build: ./backend/agent-autonomo-ts
    ports:
      - "3005:3005"
    env_file:
      - ./backend/agent-autonomo-ts/.env
    depends_on:
      - feedback-ia-python
    networks:
      - exposia-net

  feedback-ia-python:
    build: ./backend/feedback-ia-python
    ports:
      - "8000:8000"
    networks:
      - exposia-net

networks:
  exposia-net:
    driver: bridge
