version: '3.8'

services:
  db-presentaciones:
    image: postgres:15
    container_name: presentaciones_postgres
    ports:
      - '5435:5432'  # Puerto externo 5435 para evitar conflicto
    environment:
      POSTGRES_USER: exposia
      POSTGRES_PASSWORD: exposia123
      POSTGRES_DB: exposia_db
    volumes:
      - presentaciones_pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  presentaciones-php:
    build: .
    container_name: presentaciones_php
    ports:
      - '8001:80'  # Puerto externo 8001 para Apache
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: db-presentaciones
      DB_PORT: 5432
      DB_DATABASE: exposia_db
      DB_USERNAME: exposia
      DB_PASSWORD: exposia123
    depends_on:
      - db-presentaciones
    restart: unless-stopped
    # Si tienes un .env, puedes montar aquí
    # env_file:
    #   - .env

volumes:
  presentaciones_pgdata:
